version: "3.3"
services:
    postgresdb:
        image: postgres
        hostname: postgres-host      
        environment:
            POSTGRES_DATABASE: "db"
            # So you don't have to use root, but you can if you like
            POSTGRES_USER: "user"
            # You can use whatever password you like
            POSTGRES_PASSWORD: "password"
            # Password for root access
            POSTGRES_ROOT_PASSWORD: "password"
        ports:
            - "5432:5432"
        expose:
            # Opens port 3306 on the container
            - "5432"
            # Where our data will be persisted
        volumes:
            - my-db-postgres:/var/lib/postgres
            - "/etc/localtime:/etc/localtime:ro"
        command:
            - "postgres"
            - "-c"
            - "wal_level=logical"
# Names our volume
volumes:
    my-db-postgres:
